Repository itslupus/gamersnet, pull requests merged in 2021-02, with the labels that each got.

#58 Added basic testing to test testing
  gamersnet_backend/.env
  gamersnet_backend/README.md
  gamersnet_backend/__tests__/testPage1.js
  gamersnet_backend/__tests__/testTrue.js
  gamersnet_backend/app.js
  gamersnet_backend/index.js
  gamersnet_backend/package-lock.json
  gamersnet_backend/package.json
Labels: dev task

#65 Frontend register
  gamersnet_backend/routes/users/authenticate.js
  gamersnet_backend/routes/users/createAccount.js
  gamersnet_frontend/.gitignore
  gamersnet_frontend/package-lock.json
  gamersnet_frontend/src/api.js
  gamersnet_frontend/src/components/PrivateRoute.js
  gamersnet_frontend/src/components/header/index.js
  gamersnet_frontend/src/components/header/styles.css
  gamersnet_frontend/src/components/home/index.js
  gamersnet_frontend/src/components/logout/index.js
  gamersnet_frontend/src/components/page2/index.js
  gamersnet_frontend/src/components/password/index.js
  gamersnet_frontend/src/components/register/index.js
  gamersnet_frontend/src/components/register/styles.css
  gamersnet_frontend/src/components/signin/index.js
  gamersnet_frontend/src/components/signin/styles.css
  gamersnet_frontend/src/cookieCheck.js
  gamersnet_frontend/src/index.js
  gamersnet_frontend/src/styles.css
Labels: dev task, high priority

#70 Added testing plan
  .github/test_plan.pdf
Labels: documentation
